crud_projects/crud_projects/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('schools_app/', include('schools_app.urls')),
    path('todo_app1', include('todo_app1.urls'))

]

crud_projects/home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('accounts/', include('django.contrib.auth.urls'), name ='login'), 
    path("signup/", views.SignUp.as_view(), name='signup'),
    path('logout/', views.logout_view, name='logout'),
]

crud_projects/schools_app/urls.py
from django.urls import path
from . import views

app_name = 'schools_app'

urlpatterns = [
    path('school/list',views.SchoolListView.as_view(),name='school_list'),
    path('school/detail/<int:pk>/',views.SchoolDetailView.as_view(),name='school_detail'),
    path('school/create/',views.SchoolCreateView.as_view(),name='school_create'),
    path('school/update/<int:pk>/',views.SchoolUpdateView.as_view(),name='school_update'),
    path('school/delete/<int:pk>/',views.SchoolDeleteView.as_view(),name='school_delete')
]

crud_projects/todo_app1/urls.py
from django.urls import path
from . import views

app_name = 'todo_app1'

urlpatterns = [
	path('', views.index, name="task_list"),
	path('update_task/<str:pk>/', views.updateTask, name="update_task"),
	path('delete_task/<str:pk>/', views.deleteTask, name="delete_task"),
]

crud_projects/home/models.py
from django.db import models

# Create your models here.

crud_projects/schools_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail",kwargs={'pk':self.pk})

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='students',on_delete=models.CASCADE)

    def __str__(self):
        return self.name

crud_projects/todo_app1/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
	title = models.CharField(max_length=200)
	complete = models.BooleanField(default=False)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.title

crud_projects/todo_app1/forms.py
from django import forms
from django.forms import ModelForm

from .models import *


class TaskForm(forms.ModelForm):
	title= forms.CharField(widget= forms.TextInput(attrs={'placeholder':'Add new task...'}))

	class Meta:
		model = Task
		fields = '__all__'

crud_projects/home/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import logout, login 
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView

# Create your views here.

# This is a little complex because we need to detect when we are
# running in various configurations

class HomeView(View):
    def get(self, request):
        context = {
        }
        return render(request, 'home/main.html', context)

def logout_view(request):
  logout(request)
  return redirect("/")

class SignUp(CreateView):
   form_class = UserCreationForm
   success_url = reverse_lazy('home:login')
   template_name = 'registration/signup.html'

crud_projects/schools_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
                                ListView,DetailView,
                                CreateView,DeleteView,
                                UpdateView)
from .models import *
from django.contrib.auth.mixins import LoginRequiredMixin

class SchoolListView(LoginRequiredMixin, ListView):
    model = School
    # Default would be 'school_list'
    # Example of making your own:
    # context_object_name = 'schools'
    
class SchoolDetailView(LoginRequiredMixin,DetailView):
    context_object_name = 'school_details'
    model = School
    template_name = 'schools_app/school_detail.html'


class SchoolCreateView(LoginRequiredMixin,CreateView):
    fields = ("name","principal","location")
    model = School


class SchoolUpdateView(LoginRequiredMixin,UpdateView):
    fields = ("name","principal")
    model = School

class SchoolDeleteView(LoginRequiredMixin,DeleteView):
    model = School
    success_url = reverse_lazy("schools_app:school_list")

crud_projects/todo_app1/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import *
from .forms import *

# Create your views here.
@login_required
def index(request):
	tasks = Task.objects.all()

	form = TaskForm()

	if request.method =='POST':
		form = TaskForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('/')


	context = {'tasks':tasks, 'form':form}
	return render(request, 'todo_app1/task_list.html', context)
@login_required
def updateTask(request, pk):
	task = Task.objects.get(id=pk)

	form = TaskForm(instance=task)

	if request.method == 'POST':
		form = TaskForm(request.POST, instance=task)
		if form.is_valid():
			form.save()
			return redirect('/')

	context = {'form':form}

	return render(request, 'todo_app1/update_task.html', context)

    
@login_required
def deleteTask(request, pk):
	item = Task.objects.get(id=pk)

	if request.method == 'POST':
		item.delete()
		return redirect('/')

	context = {'item':item}
	return render(request, 'todo_app1/delete_task.html', context)

crud_projects/home/templates/home/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CRUD PROJECTS</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home:home' %}">CRUD PROJECTS</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              {% if user.is_authenticated %}
              <a class="nav-link" href=" {% url 'home:logout' %}">Logout</a>
              <a class="nav-link " href="{% url 'admin:index' %}">Admin</a>
              {% else %}
              <a class="nav-link" href="{% url 'home:login' %}">Login</a>
              <a class="nav-link" href="{% url 'home:signup' %}">SignUp</a>
              {% endif %}
              
            </div>
          </div>
        </div>
      </nav>
    <div class="container">
      <div class="jumbotron">
        {% block body_block %}
  
        {% endblock %}
      </div>
    </div>
  
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>

crud_projects/home/templates/home/main.html
{% extends 'home/base.html' %}

{% block body_block %}

<div class="jumbotron">
    <h1> Welcome to my CRUD Projects! </h1>
    <li><a href="{% url 'schools_app:school_list' %}" >SCHOOL CRUD APP</a> 
    </li>
    <li><a href="{% url 'todo_app1:task_list' %}" >TODO CRUD APP 1 </a> 
    </li>
</div>

{% endblock  %}

crud_projects/schools_app/templates/schools_app/school_confirm_delete.html
{% extends "home/base.html" %}

{% block body_block %}
<h1>Delete {{school.name}}?</h1>

<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Confirm">
  <a href="{% url 'schools_app:school_detail' pk=school.pk %} ">Cancel</a>

</form>

{% endblock %}

crud_projects/schools_app/templates/schools_app/school_detail.html
{% extends "home/base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Welcome to the School Detail Page</h1>
    <h2>School Details:</h2>
    <p>Id_num: {{school_details.id}}</p>
    <p>Name: {{school_details.name}}</p>
    <p>Principal: {{school_details.principal}}</p>
    <p>Location: {{school_details.location}}</p>
    <h3>Students:</h3>

      {% for student in school_details.students.all %}
        <p>{{student.name}} who is {{student.age}} years old.</p>
      {% endfor %}

  </div>
  <div class="container">
    <p><a class='btn btn-warning' href="{% url 'schools_app:school_update' pk=school_details.pk %}">Update</a></p>

  </div>
  <div class="container">
    <p><a class='btn btn-warning' href="{% url 'schools_app:school_delete' pk=school_details.pk %}">Delete</a></p>

  </div>


{% endblock %}

crud_projects/schools_app/templates/schools_app/school_form.html
{% extends "home/base.html" %}

{% block body_block %}
<h1>
  {% if not form.instance.pk %}
  Create School
  {% else %}
  Update School
  {% endif %}
</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class='btn btn-primary' value="Submit">

  </form>


{% endblock %}

crud_projects/schools_app/templates/schools_app/school_list.html
{% extends "home/base.html" %}
{% block body_block %}

    <h1>Welcome to the List of Schools Page!</h1>
      <ol>
        {% for school in school_list %}
          <h2><li><a href="{% url 'schools_app:school_detail' school.id %}"> {{school.name}} </a></li></h2>
        {% endfor %}
      </ol>

{% endblock %}

crud_projects/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CRUD PROJECTS</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">CRUD PROJECTS</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
              <a class="nav-link" href="{% url 'schools_app:school_list' %}">Schools App</a>
              <a class="nav-link" href="#">Cats App</a>
              <a class="nav-link " href="{% url 'admin:index' %}">Admin</a>
            </div>
          </div>
        </div>
      </nav>
    <div class="container">
        {% block body_block %}
  
        {% endblock %}
    </div>
  
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>

crud_projects/todo_app1/templates/todo_app1/task_delete.html
<p>Are you sure you want to delete "{{item}}"?</p>

<a href="{% url 'task_list' %}" >Cancel</a>

<form method="POST" action="">
	{% csrf_token %}
	<input type="submit" name="Confirm">
</form>

crud_projects/todo_app1/templates/todo_app1/task_list.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<style>

	body{
		background-color: #638CB8;
	}

	input{
		width: 100%;
		padding: 12px 20px;
		margin: 8px 0;
		box-sizing: border-box;
	}

	input::placeholder {
	  color: #d3d3d3;
	}

	.submit{
		background-color: #6BA3E8;
	}

	.center-column{
		width:600px;
		margin: 20px auto;
		padding:20px;
		background-color: #fff;
		border-radius: 3px;
		box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75);
	}

	.item-row{
		background-color: #906abd;
		margin: 10px;
		padding: 20px;
		border-radius: 3px;
		color: #fff;
		font-size: 16px;
		box-shadow: 0px -1px 10px -4px rgba(0,0,0,0.75);
	}

	.btn-danger{
		background-color: #ffae19;
		border-color: #e59400;
	}

</style>

<div class="center-column">

	<form method="POST" action="/">
		{% csrf_token %}
		{{form.title}}
		<input class="btn btn-info" type="submit" name="Create Task">
	</form>

	<div class="todo-list">

	{% for task in tasks %}
		<div class="item-row">
			<a class="btn btn-sm btn-info" href="{% url 'todo_app1:update_task' task.id %}">Update</a>
			<a class="btn btn-sm btn-danger" href="{% url 'todo_app1:delete_task' task.id %}">Delete</a>

			{% if task.complete == True %}
			<strike>{{task}}</strike>
			{% else %}
			<span>{{task}}</span>
			{% endif %}
		</div>
	{% endfor %}
	</div>
</div>

crud_projects/todo_app1/templates/todo_app1/task_update.html
<h3>Update Task</h3>

<form method="POST" action="">
	{% csrf_token %}

	{{form}}
	<input type="submit" name="Update Task">
	
	
</form>